default_context:
  project_name: 'db_api_protection'
  project_slug: 'dev-api'
  domain_main: 'dev-api.com'
  domain_staging: 'stag.dev-api.com'
  docker_swarm_stack_name_main: 'dev-api-com'
  docker_swarm_stack_name_staging: 'stag-dev-api-com'
  secret_key: '11b58569c2e8c42d289c416e52d52132334a1a3852d1438818f6d70649d3e674'
  first_superuser: 'admin@dev-api.com'
  first_superuser_password: '44dc73ea4f8e8b13595ec3a6c905c639'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.dev-api.com", "https://stag.dev-api.com", "https://dev-api.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@dev-api.com'
  postgres_password: '44dc73ea4f8e8b13595ec3a6c905c639'
  pgadmin_default_user: 'admin@dev-api.com'
  pgadmin_default_user_password: '44dc73ea4f8e8b13595ec3a6c905c639'
  traefik_constraint_tag: 'dev-api.com'
  traefik_constraint_tag_staging: 'stag.dev-api.com.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:44dc73ea4f8e8b13595ec3a6c905c639'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
